### ISSUE TITLE
Wrong typo and Module build failed

### ISSUE THREAD

**Issue by dangquang1020** [FabianGosebrink/ASPNET-Foodchooser-Cross-Platform-Angular2#1]
I found wrong typo in some file, I have fixed it but when I run gulp build command, the console log print this "Module build failed: ReferenceError: Promise is not defined ".

Could you fix it and push again.
Thanks.

**Comment by FabianGosebrink** [comment]
Hey @dangquang1020,

which gulp command do you mean? I just ran the `gulp build:web:prod` without problems.

BR

Fabian

**Comment by dangquang1020** [comment]
Hi Fabian,
Very sorry, its seem my mistake. Now I can build and run this project.

Thank you for your project, its help me learn more about Gulp and Webpack 👍
